#!/bin/bash

if `nc -z proxy-dmz.intel.com 911 2>&1 | grep -q succeeded ` ; then
	export http_proxy=http://proxy-dmz.intel.com:912
	export https_proxy=http://proxy-dmz.intel.com:912
	export socks_proxy=socks5://proxy-dmz.intel.com:1080
	export no_proxy="127.0.0.1,localhost,.intel.com,.internal,.local,git.ops.smartperimeter.io,gateway.smart-edge.dev,ui.smart-edge.dev,.irv-colo.smart-edge.net"
	export proxy_status=proxy_yes
	git config --global http.proxy http://proxy-dmz.intel.com:912
	git config --global https.proxy http://proxy-dmz.intel.com:912
	npm config set proxy http://proxy-dmz.intel.com:912
	npm config set https-proxy http://proxy-dmz.intel.com:912

	# Set prompt to Blue for on VPN
	export PS1="\e[${Blueshell}m[\u@\h \W]\$ \e[m"
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo "!! Intel proxies detected !!"
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
else
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo "!! Intel proxies unset !!"
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
	unset http_proxy
	unset https_proxy
	unset socks_proxy
	unset no_proxy
	export proxy_status=no_proxy
	git config --global --unset http.proxy
	git config --global --unset https.proxy
	npm config delete proxy https-proxy
	# Set prompt to cyan for off VPN
	export PS1="\e[${Cyanshell}m[\u@\h \W]\$ \e[m"
fi
