#!/bin/bash


enable() {
    gsettings set org.gnome.system.proxy mode manual
    gsettings set org.gnome.system.proxy.http host "$HTTP_PROXY_HOST"
    gsettings set org.gnome.system.proxy.http port "$HTTP_PROXY_PORT"
    gsettings set org.gnome.system.proxy.https host "$HTTPS_PROXY_HOST"
    gsettings set org.gnome.system.proxy.https port "$HTTPS_PROXY_PORT"

    sudo sed -i.bak '/http[s]::proxy/Id' /etc/apt/apt.conf
    sudo tee -a /etc/apt/apt.conf <<EOF
Acquire::http::proxy "http://$HTTP_PROXY_HOST:$HTTP_PROXY_PORT/";
Acquire::https::proxy "http://$HTTPS_PROXY_HOST:$HTTPS_PROXY_PORT/";
EOF

sudo sed -i.bak '/http[s]_proxy/Id' /etc/environment
sudo tee -a /etc/environment <<EOF
http_proxy="http://$HTTP_PROXY_HOST:$HTTP_PROXY_PORT/"
https_proxy="http://$HTTPS_PROXY_HOST:$HTTPS_PROXY_PORT/"
EOF

export http_proxy="http://$HTTP_PROXY_HOST:$HTTP_PROXY_PORT/"
export https_proxy="http://$HTTPS_PROXY_HOST:$HTTPS_PROXY_PORT/"
}

disable() {
    gsettings set org.gnome.system.proxy mode none
    sudo mv /etc/apt/apt.conf.bak /etc/apt/apt.conf
    sudo mv /etc/environment.bak /etc/environment
}

status() {
    echo proxy settings
    gsettings get org.gnome.system.proxy mode
}

main() {
    op=${1-enable}
    shift

    [ "$op" = "enable" ] && enable "$@"
    [ "$op" = "disable" ] && disable "$@"
    [ "$op" = "status" ] && status "$@"
}

HTTP_PROXY_HOST=proxy-iil.intel.com
HTTP_PROXY_PORT=911
HTTPS_PROXY_HOST=proxy-iil.intel.com
HTTPS_PROXY_PORT=911
NO_PROXY=intel.com,.intel.com,localhost,127.0.0.1

main "$@"
